import Link from "~src/lib/components/Link";
import { t } from "~src/lib/services/translations";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: React.PropsWithChildren<{}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <h1>
              <Link href="/">{t("TITLE")}</Link>
            </h1>
            <div style={{ display: "flex", gap: "1em" }}>
              <Link href="/demo/simple-suspense">demo #1</Link>
              <Link href="/demo/without-suspense">demo #2</Link>
              <Link href="/demo/with-suspense">demo #3</Link>
            </div>
          </div>
          <hr />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
